-- MEM-110: per-Tenant Code Interpreter switch and files generated by run_python.
CREATE TABLE chat_interpreter_setting (
    tenant_id UUID PRIMARY KEY REFERENCES tenants(id),
    enabled BOOLEAN NOT NULL,
    revision BIGINT NOT NULL CHECK (revision > 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE chat_file_artifact (
    id UUID PRIMARY KEY,
    tenant_id UUID NOT NULL REFERENCES tenants(id),
    message_id UUID NOT NULL,
    stored_object_id UUID NOT NULL,
    object_key VARCHAR(240) NOT NULL,
    filename VARCHAR(200) NOT NULL,
    media_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL CHECK (size_bytes >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX chat_file_artifact_message ON chat_file_artifact(tenant_id, message_id);
