// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { createInvitation, getCurrentIdentity, getCurrentInvitation, listInvitations, type Options, revokeInvitation, rotateInvitation } from '../sdk.gen';
import type { CreateInvitationData, CreateInvitationError, CreateInvitationResponse, GetCurrentIdentityData, GetCurrentIdentityResponse, GetCurrentInvitationData, GetCurrentInvitationError, GetCurrentInvitationResponse, ListInvitationsData, ListInvitationsError, ListInvitationsResponse, RevokeInvitationData, RevokeInvitationError, RevokeInvitationResponse, RotateInvitationData, RotateInvitationError, RotateInvitationResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getCurrentIdentityQueryKey = (options?: Options<GetCurrentIdentityData>) => createQueryKey('getCurrentIdentity', options);

/**
 * Return the authenticated MemoryOS actor
 *
 * Accepts either an existing MemoryOS browser session or a valid bound bearer identity and returns only the stable internal ActorId.
 */
export const getCurrentIdentityOptions = (options?: Options<GetCurrentIdentityData>) => queryOptions<GetCurrentIdentityResponse, DefaultError, GetCurrentIdentityResponse, ReturnType<typeof getCurrentIdentityQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentIdentity({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentIdentityQueryKey(options)
});

export const listInvitationsQueryKey = (options?: Options<ListInvitationsData>) => createQueryKey('listInvitations', options);

/**
 * List the current owner's Organization invitations
 */
export const listInvitationsOptions = (options?: Options<ListInvitationsData>) => queryOptions<ListInvitationsResponse, ListInvitationsError, ListInvitationsResponse, ReturnType<typeof listInvitationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await listInvitations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: listInvitationsQueryKey(options)
});

/**
 * Create one Organization member invitation
 */
export const createInvitationMutation = (options?: Partial<Options<CreateInvitationData>>): UseMutationOptions<CreateInvitationResponse, CreateInvitationError, Options<CreateInvitationData>> => {
    const mutationOptions: UseMutationOptions<CreateInvitationResponse, CreateInvitationError, Options<CreateInvitationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await createInvitation({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Revoke a pending invitation
 */
export const revokeInvitationMutation = (options?: Partial<Options<RevokeInvitationData>>): UseMutationOptions<RevokeInvitationResponse, RevokeInvitationError, Options<RevokeInvitationData>> => {
    const mutationOptions: UseMutationOptions<RevokeInvitationResponse, RevokeInvitationError, Options<RevokeInvitationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await revokeInvitation({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Replace the secret of a pending invitation
 */
export const rotateInvitationMutation = (options?: Partial<Options<RotateInvitationData>>): UseMutationOptions<RotateInvitationResponse, RotateInvitationError, Options<RotateInvitationData>> => {
    const mutationOptions: UseMutationOptions<RotateInvitationResponse, RotateInvitationError, Options<RotateInvitationData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await rotateInvitation({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCurrentInvitationQueryKey = (options?: Options<GetCurrentInvitationData>) => createQueryKey('getCurrentInvitation', options);

/**
 * Return the redacted invitation landing context from the browser session
 */
export const getCurrentInvitationOptions = (options?: Options<GetCurrentInvitationData>) => queryOptions<GetCurrentInvitationResponse, GetCurrentInvitationError, GetCurrentInvitationResponse, ReturnType<typeof getCurrentInvitationQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCurrentInvitation({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCurrentInvitationQueryKey(options)
});
