import {
  BarChart3,
  Bot,
  BookOpen,
  Briefcase,
  Calculator,
  FileText,
  Landmark,
  Lightbulb,
  MessageSquare,
  Scale,
  Search,
  ShieldCheck,
  Users,
  type LucideIcon,
} from "lucide-react";
/** Icon choices offered by the agent editor; the server stores only the key. */
export const agentIcons: Record<string, LucideIcon> = {
  bot: Bot,
  chart: BarChart3,
  finance: Landmark,
  calculator: Calculator,
  people: Users,
  legal: Scale,
  document: FileText,
  book: BookOpen,
  briefcase: Briefcase,
  search: Search,
  idea: Lightbulb,
  shield: ShieldCheck,
  chat: MessageSquare,
};
