spring:
  datasource:
    url: ${MEMORYOS_DATABASE_URL:jdbc:postgresql://localhost:55432/arconia}
    username: ${MEMORYOS_DATABASE_USERNAME:arconia}
    password: ${MEMORYOS_DATABASE_PASSWORD:arconia}

arconia:
  dev:
    services:
      redis:
        port: 56379
