spring:
  datasource:
    url: ${MEMORYOS_DATABASE_URL:jdbc:postgresql://localhost:55432/arconia}
    username: ${MEMORYOS_DATABASE_USERNAME:arconia}
    password: ${MEMORYOS_DATABASE_PASSWORD:arconia}
  data:
    redis:
      host: ${MEMORYOS_REDIS_HOST:localhost}
      port: ${MEMORYOS_REDIS_PORT:56379}
