// This file is auto-generated by @hey-api/openapi-ts

export { getCurrentIdentity, type Options } from './sdk.gen';
export type { ClientOptions, CurrentIdentity, GetCurrentIdentityData, GetCurrentIdentityErrors, GetCurrentIdentityResponse, GetCurrentIdentityResponses } from './types.gen';
