// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { CreateFileSourceData, CreateFileSourceResponses, CreateInvitationData, CreateInvitationErrors, CreateInvitationResponses, DeleteSourceData, DeleteSourceResponses, GetCurrentIdentityData, GetCurrentIdentityErrors, GetCurrentIdentityResponses, GetCurrentInvitationData, GetCurrentInvitationErrors, GetCurrentInvitationResponses, GetSourceData, GetSourceOperationData, GetSourceOperationResponses, GetSourceResponses, ListInvitationsData, ListInvitationsErrors, ListInvitationsResponses, ListSourceIndexAttemptsData, ListSourceIndexAttemptsResponses, ListSourceItemsData, ListSourceItemsResponses, ListSourcesData, ListSourcesResponses, ReindexSourceItemData, ReindexSourceItemResponses, RemoveSourceItemData, RemoveSourceItemResponses, RevokeInvitationData, RevokeInvitationErrors, RevokeInvitationResponses, RotateInvitationData, RotateInvitationErrors, RotateInvitationResponses, UploadSourceItemData, UploadSourceItemResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List current source items
 */
export const listSourceItems = <ThrowOnError extends boolean = false>(options: Options<ListSourceItemsData, ThrowOnError>): RequestResult<ListSourceItemsResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListSourceItemsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }],
    url: '/api/sources/{sourceId}/items',
    ...options
});

/**
 * Upload one bounded FILE source item
 */
export const uploadSourceItem = <ThrowOnError extends boolean = false>(options: Options<UploadSourceItemData, ThrowOnError>): RequestResult<UploadSourceItemResponses, unknown, ThrowOnError> => (options.client ?? client).post<UploadSourceItemResponses, unknown, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }],
    url: '/api/sources/{sourceId}/items',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Start durable source item removal
 */
export const removeSourceItem = <ThrowOnError extends boolean = false>(options: Options<RemoveSourceItemData, ThrowOnError>): RequestResult<RemoveSourceItemResponses, unknown, ThrowOnError> => (options.client ?? client).post<RemoveSourceItemResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }],
    url: '/api/sources/{sourceId}/items/{itemId}/remove',
    ...options
});

/**
 * Reindex one source item
 */
export const reindexSourceItem = <ThrowOnError extends boolean = false>(options: Options<ReindexSourceItemData, ThrowOnError>): RequestResult<ReindexSourceItemResponses, unknown, ThrowOnError> => (options.client ?? client).post<ReindexSourceItemResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }],
    url: '/api/sources/{sourceId}/items/{itemId}/index-attempts',
    ...options
});

/**
 * Start durable source deletion
 */
export const deleteSource = <ThrowOnError extends boolean = false>(options: Options<DeleteSourceData, ThrowOnError>): RequestResult<DeleteSourceResponses, unknown, ThrowOnError> => (options.client ?? client).post<DeleteSourceResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }],
    url: '/api/sources/{sourceId}/delete',
    ...options
});

/**
 * Create an Organization-owned FILE source
 */
export const createFileSource = <ThrowOnError extends boolean = false>(options: Options<CreateFileSourceData, ThrowOnError>): RequestResult<CreateFileSourceResponses, unknown, ThrowOnError> => (options.client ?? client).post<CreateFileSourceResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }],
    url: '/api/sources/file',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List the current owner's Organization invitations
 */
export const listInvitations = <ThrowOnError extends boolean = false>(options?: Options<ListInvitationsData, ThrowOnError>): RequestResult<ListInvitationsResponses, ListInvitationsErrors, ThrowOnError> => (options?.client ?? client).get<ListInvitationsResponses, ListInvitationsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/invitations',
    ...options
});

/**
 * Create one Organization member invitation
 */
export const createInvitation = <ThrowOnError extends boolean = false>(options: Options<CreateInvitationData, ThrowOnError>): RequestResult<CreateInvitationResponses, CreateInvitationErrors, ThrowOnError> => (options.client ?? client).post<CreateInvitationResponses, CreateInvitationErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/invitations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Replace the secret of a pending invitation
 */
export const rotateInvitation = <ThrowOnError extends boolean = false>(options: Options<RotateInvitationData, ThrowOnError>): RequestResult<RotateInvitationResponses, RotateInvitationErrors, ThrowOnError> => (options.client ?? client).post<RotateInvitationResponses, RotateInvitationErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/invitations/{invitationId}/rotate',
    ...options
});

/**
 * Revoke a pending invitation
 */
export const revokeInvitation = <ThrowOnError extends boolean = false>(options: Options<RevokeInvitationData, ThrowOnError>): RequestResult<RevokeInvitationResponses, RevokeInvitationErrors, ThrowOnError> => (options.client ?? client).post<RevokeInvitationResponses, RevokeInvitationErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/invitations/{invitationId}/revoke',
    ...options
});

/**
 * List Organization sources
 */
export const listSources = <ThrowOnError extends boolean = false>(options?: Options<ListSourcesData, ThrowOnError>): RequestResult<ListSourcesResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ListSourcesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }],
    url: '/api/sources',
    ...options
});

/**
 * Get one source with current items
 */
export const getSource = <ThrowOnError extends boolean = false>(options: Options<GetSourceData, ThrowOnError>): RequestResult<GetSourceResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetSourceResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }],
    url: '/api/sources/{sourceId}',
    ...options
});

/**
 * List source indexing attempts
 */
export const listSourceIndexAttempts = <ThrowOnError extends boolean = false>(options: Options<ListSourceIndexAttemptsData, ThrowOnError>): RequestResult<ListSourceIndexAttemptsResponses, unknown, ThrowOnError> => (options.client ?? client).get<ListSourceIndexAttemptsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }],
    url: '/api/sources/{sourceId}/index-attempts',
    ...options
});

/**
 * Get a durable source operation
 */
export const getSourceOperation = <ThrowOnError extends boolean = false>(options: Options<GetSourceOperationData, ThrowOnError>): RequestResult<GetSourceOperationResponses, unknown, ThrowOnError> => (options.client ?? client).get<GetSourceOperationResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }, {
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }],
    url: '/api/source-operations/{operationId}',
    ...options
});

/**
 * Return the redacted invitation landing context from the browser session
 */
export const getCurrentInvitation = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentInvitationData, ThrowOnError>): RequestResult<GetCurrentInvitationResponses, GetCurrentInvitationErrors, ThrowOnError> => (options?.client ?? client).get<GetCurrentInvitationResponses, GetCurrentInvitationErrors, ThrowOnError>({ url: '/api/invitations/current', ...options });

/**
 * Return the authenticated MemoryOS actor
 *
 * Accepts either an existing MemoryOS browser session or a valid bound bearer identity and returns the stable internal ActorId plus its durable Organization authority projection.
 */
export const getCurrentIdentity = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentIdentityData, ThrowOnError>): RequestResult<GetCurrentIdentityResponses, GetCurrentIdentityErrors, ThrowOnError> => (options?.client ?? client).get<GetCurrentIdentityResponses, GetCurrentIdentityErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/identity/me',
    ...options
});
