// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateInvitationData, CreateInvitationErrors, CreateInvitationResponses, GetCurrentIdentityData, GetCurrentIdentityErrors, GetCurrentIdentityResponses, GetCurrentInvitationData, GetCurrentInvitationErrors, GetCurrentInvitationResponses, ListInvitationsData, ListInvitationsErrors, ListInvitationsResponses, RevokeInvitationData, RevokeInvitationErrors, RevokeInvitationResponses, RotateInvitationData, RotateInvitationErrors, RotateInvitationResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * List the current owner's Organization invitations
 */
export const listInvitations = <ThrowOnError extends boolean = false>(options?: Options<ListInvitationsData, ThrowOnError>): RequestResult<ListInvitationsResponses, ListInvitationsErrors, ThrowOnError> => (options?.client ?? client).get<ListInvitationsResponses, ListInvitationsErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/invitations',
    ...options
});

/**
 * Create one Organization member invitation
 */
export const createInvitation = <ThrowOnError extends boolean = false>(options: Options<CreateInvitationData, ThrowOnError>): RequestResult<CreateInvitationResponses, CreateInvitationErrors, ThrowOnError> => (options.client ?? client).post<CreateInvitationResponses, CreateInvitationErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/invitations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Replace the secret of a pending invitation
 */
export const rotateInvitation = <ThrowOnError extends boolean = false>(options: Options<RotateInvitationData, ThrowOnError>): RequestResult<RotateInvitationResponses, RotateInvitationErrors, ThrowOnError> => (options.client ?? client).post<RotateInvitationResponses, RotateInvitationErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/invitations/{invitationId}/rotate',
    ...options
});

/**
 * Return the redacted invitation landing context from the browser session
 */
export const getCurrentInvitation = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentInvitationData, ThrowOnError>): RequestResult<GetCurrentInvitationResponses, GetCurrentInvitationErrors, ThrowOnError> => (options?.client ?? client).get<GetCurrentInvitationResponses, GetCurrentInvitationErrors, ThrowOnError>({ url: '/api/invitations/current', ...options });

/**
 * Return the authenticated MemoryOS actor
 *
 * Accepts either an existing MemoryOS browser session or a valid bound bearer identity and returns the stable internal ActorId plus its durable Organization authority projection.
 */
export const getCurrentIdentity = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentIdentityData, ThrowOnError>): RequestResult<GetCurrentIdentityResponses, GetCurrentIdentityErrors, ThrowOnError> => (options?.client ?? client).get<GetCurrentIdentityResponses, GetCurrentIdentityErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/identity/me',
    ...options
});

/**
 * Revoke a pending invitation
 */
export const revokeInvitation = <ThrowOnError extends boolean = false>(options: Options<RevokeInvitationData, ThrowOnError>): RequestResult<RevokeInvitationResponses, RevokeInvitationErrors, ThrowOnError> => (options.client ?? client).delete<RevokeInvitationResponses, RevokeInvitationErrors, ThrowOnError>({
    security: [{
            in: 'cookie',
            name: 'SESSION',
            type: 'apiKey'
        }, { scheme: 'bearer', type: 'http' }],
    url: '/api/invitations/{invitationId}',
    ...options
});
