// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CurrentIdentity = {
    /**
     * Stable internal MemoryOS actor identifier.
     */
    actorId: string;
};

export type GetCurrentIdentityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/identity/me';
};

export type GetCurrentIdentityErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
};

export type GetCurrentIdentityResponses = {
    /**
     * The authenticated actor
     */
    200: CurrentIdentity;
};

export type GetCurrentIdentityResponse = GetCurrentIdentityResponses[keyof GetCurrentIdentityResponses];
