// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ReplaceUserGroupsRequest = {
    groupIds: Array<string>;
};

export type InitiateSourceUploadRequest = {
    filename: string;
    mediaType: string;
    sizeBytes: number;
    sha256: string;
};

export type SourceUploadAuthorization = {
    uploadId: string;
    method: string;
    uploadUrl: string;
    requiredHeaders: {
        [key: string]: string;
    };
    expiresAt: string;
};

export type SourceItem = {
    id: string;
    filename: string;
    sha256: string;
    sizeBytes: number;
    status: string;
    uploadedAt: string;
    latestOperationId: string | null;
    errorCode: string | null;
};

export type SourceOperation = {
    id: string;
    type: string;
    status: string;
    createdAt: string;
    completedAt: string | null;
    errorCode: string | null;
};

export type SourceUploadReceipt = {
    item: SourceItem;
    operation: SourceOperation;
};

export type UpdateSourceGroupsRequest = {
    groupIds: Array<string>;
};

export type CreateFileSourceRequest = {
    name: string;
    groupIds?: Array<string> | null;
};

export type SourceDetail = {
    source: SourceSummary;
    items: Array<SourceItem>;
};

export type SourceSummary = {
    id: string;
    name: string;
    type: string;
    access: string;
    status: string;
    pendingWork: boolean;
    documentCount: number;
    lastSucceededAt: string | null;
    errorCode: string | null;
    actions: Array<string>;
};

export type CreateInvitationRequest = {
    email: string;
};

export type Invitation = {
    id: string;
    email: string;
    status: 'PENDING' | 'ACCEPTED' | 'EXPIRED' | 'REVOKED';
    createdAt: string;
    expiresAt: string;
    acceptedActorId?: string | null;
    acceptedAt?: string | null;
    revokedAt?: string | null;
};

export type IssuedInvitation = {
    invitation: Invitation;
    /**
     * Relative same-origin capability URL returned only from create or rotate.
     */
    invitationUrl: string;
    /**
     * Observable delivery result for this issue or rotation operation.
     */
    delivery: 'ACTIVATION_EMAIL_SENT' | 'EXISTING_ACCOUNT' | 'RECOVERY_LINK_ONLY';
};

export type CreateGroupRequest = {
    name: string;
};

export type GroupSummary = {
    id: string;
    name: string;
    systemKey: GroupSystemKey | null;
    memberCount: number;
    managerCount: number;
    capabilities: Array<'IAM_ADMIN' | 'USERS_MANAGE' | 'GROUPS_READ' | 'GROUPS_MANAGE' | 'SOURCES_READ' | 'SOURCES_MANAGE' | 'SOURCES_DELETE'>;
    actions: Array<string>;
};

export type GroupSystemKey = 'ADMIN' | 'BASIC';

export type RenameGroupRequest = {
    name: string;
};

export type AddGroupMembersRequest = {
    actorIds: Array<string>;
};

export type ReplaceGroupCapabilitiesRequest = {
    capabilities: Array<'IAM_ADMIN' | 'USERS_MANAGE' | 'GROUPS_READ' | 'GROUPS_MANAGE' | 'SOURCES_READ' | 'SOURCES_MANAGE' | 'SOURCES_DELETE'>;
};

export type AccountType = 'STANDARD';

export type TenantMembershipRole = 'OWNER' | 'MEMBER';

export type UserCounts = {
    active: number;
    inactive: number;
    invited: number;
};

export type UserGroup = {
    id: string;
    name: string;
    systemKey: GroupSystemKey | null;
};

export type UserListItem = {
    /**
     * Stable Actor identifier for a membership row; null for an invitation row.
     */
    actorId: string | null;
    /**
     * Invitation identifier for an invited row; null for a membership row.
     */
    invitationId: string | null;
    displayName: string | null;
    email: string | null;
    emailVerified: boolean | null;
    profileIssuer: string | null;
    role: TenantMembershipRole | null;
    accountType: AccountType | null;
    status: 'ACTIVE' | 'INACTIVE' | 'INVITED';
    groups: Array<UserGroup>;
    /**
     * Invitation expiry for an invited row; null for a membership row.
     */
    invitationExpiresAt: string | null;
};

export type UserPage = {
    items: Array<UserListItem>;
    page: number;
    size: number;
    totalItems: number;
    totalPages: number;
    counts: UserCounts;
};

export type SourceGroup = {
    id: string;
    name: string;
    systemKey: GroupSystemKey | null;
};

export type SourceGroupList = {
    items: Array<SourceGroup>;
};

export type SourceGroupPage = {
    items: Array<SourceGroup>;
    page: number;
    size: number;
    totalItems: number;
    totalPages: number;
};

export type InvitationPage = {
    items: Array<Invitation>;
    page: number;
    size: number;
    totalItems: number;
    totalPages: number;
};

export type CurrentInvitation = {
    tenantDisplayName: string;
    expiresAt: string;
    continueUrl: string;
};

export type CurrentIdentity = {
    /**
     * Stable internal MemoryOS actor identifier.
     */
    actorId: string;
    /**
     * Active Tenant context, or null when the actor has no active Tenant membership.
     */
    tenant: CurrentTenant | null;
    /**
     * Expanded global capabilities backed by current server enforcement.
     */
    capabilities: Array<'IAM_ADMIN' | 'USERS_MANAGE' | 'GROUPS_READ' | 'GROUPS_MANAGE' | 'SOURCES_READ' | 'SOURCES_MANAGE' | 'SOURCES_DELETE'>;
    /**
     * Eligible capabilities available only within resources managed by this actor.
     */
    scopedCapabilities: Array<'IAM_ADMIN' | 'USERS_MANAGE' | 'GROUPS_READ' | 'GROUPS_MANAGE' | 'SOURCES_READ' | 'SOURCES_MANAGE' | 'SOURCES_DELETE'>;
    /**
     * Monotonic Tenant IAM revision used only to invalidate private client data.
     */
    authorizationVersion: number;
};

export type CurrentTenant = {
    /**
     * Display name of the actor's active Tenant.
     */
    displayName: string;
    /**
     * Stable Tenant membership role used for presentation.
     */
    role: 'OWNER' | 'MEMBER';
};

export type GroupPage = {
    items: Array<GroupSummary>;
    page: number;
    size: number;
    totalItems: number;
    totalPages: number;
};

export type GroupSources = {
    items: Array<SourceSummary>;
};

export type GroupMember = {
    actorId: string;
    displayName: string | null;
    email: string | null;
    accountType: 'STANDARD';
    status: 'ACTIVE' | 'INACTIVE';
    isManager: boolean;
    protectedOwner: boolean;
};

export type GroupMemberPage = {
    items: Array<GroupMember>;
    page: number;
    size: number;
    totalItems: number;
    totalPages: number;
};

export type GroupCapabilities = {
    items: Array<GroupCapability>;
};

export type GroupCapability = {
    id: 'IAM_ADMIN' | 'USERS_MANAGE' | 'GROUPS_READ' | 'GROUPS_MANAGE' | 'SOURCES_READ' | 'SOURCES_MANAGE' | 'SOURCES_DELETE';
    label: string;
    description: string;
    editable: boolean;
    implies: Array<'IAM_ADMIN' | 'USERS_MANAGE' | 'GROUPS_READ' | 'GROUPS_MANAGE' | 'SOURCES_READ' | 'SOURCES_MANAGE' | 'SOURCES_DELETE'>;
};

export type ApiProblem = {
    /**
     * Stable problem type for capability failures; omitted means RFC 9457 `about:blank`.
     */
    type?: string;
    /**
     * Short human-readable problem category.
     */
    title: string;
    /**
     * HTTP status code.
     */
    status: number;
    /**
     * Safe human-readable fallback detail.
     */
    detail: string;
    /**
     * Request path that produced the problem.
     */
    instance: string;
    /**
     * Stable capability-prefixed code; present only for expected capability failures.
     */
    code?: string;
};

export type ReplaceUserGroupsData = {
    body: ReplaceUserGroupsRequest;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        actorId: string;
    };
    query?: never;
    url: '/api/users/{actorId}/groups';
};

export type ReplaceUserGroupsErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor lacks IAM_ADMIN authority or the same-origin header is missing
     */
    403: ApiProblem;
    /**
     * The user or a requested Group does not exist in the current Tenant
     */
    404: ApiProblem;
};

export type ReplaceUserGroupsError = ReplaceUserGroupsErrors[keyof ReplaceUserGroupsErrors];

export type ReplaceUserGroupsResponses = {
    /**
     * The user's ordinary Group memberships were replaced
     */
    204: void;
};

export type ReplaceUserGroupsResponse = ReplaceUserGroupsResponses[keyof ReplaceUserGroupsResponses];

export type DeactivateUserData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        actorId: string;
    };
    query?: never;
    url: '/api/users/{actorId}/deactivate';
};

export type DeactivateUserErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor lacks USERS_MANAGE authority, the target is protected, or the same-origin header is missing
     */
    403: ApiProblem;
    /**
     * The member does not exist in the current Tenant
     */
    404: ApiProblem;
};

export type DeactivateUserError = DeactivateUserErrors[keyof DeactivateUserErrors];

export type DeactivateUserResponses = {
    /**
     * The member is inactive
     */
    204: void;
};

export type DeactivateUserResponse = DeactivateUserResponses[keyof DeactivateUserResponses];

export type ActivateUserData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        actorId: string;
    };
    query?: never;
    url: '/api/users/{actorId}/activate';
};

export type ActivateUserErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor lacks USERS_MANAGE authority, the target is protected, or the same-origin header is missing
     */
    403: ApiProblem;
    /**
     * The member does not exist in the current Tenant
     */
    404: ApiProblem;
};

export type ActivateUserError = ActivateUserErrors[keyof ActivateUserErrors];

export type ActivateUserResponses = {
    /**
     * The member is active
     */
    204: void;
};

export type ActivateUserResponse = ActivateUserResponses[keyof ActivateUserResponses];

export type InitiateSourceUploadData = {
    body: InitiateSourceUploadRequest;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        sourceId: string;
    };
    query?: never;
    url: '/api/sources/{sourceId}/uploads';
};

export type InitiateSourceUploadResponses = {
    /**
     * Created
     */
    201: SourceUploadAuthorization;
};

export type InitiateSourceUploadResponse = InitiateSourceUploadResponses[keyof InitiateSourceUploadResponses];

export type FinalizeSourceUploadData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        sourceId: string;
        uploadId: string;
    };
    query?: never;
    url: '/api/sources/{sourceId}/uploads/{uploadId}/finalize';
};

export type FinalizeSourceUploadResponses = {
    /**
     * Accepted
     */
    202: SourceUploadReceipt;
};

export type FinalizeSourceUploadResponse = FinalizeSourceUploadResponses[keyof FinalizeSourceUploadResponses];

export type RemoveSourceItemData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        sourceId: string;
        itemId: string;
    };
    query?: never;
    url: '/api/sources/{sourceId}/items/{itemId}/remove';
};

export type RemoveSourceItemResponses = {
    /**
     * Accepted
     */
    202: SourceOperation;
};

export type RemoveSourceItemResponse = RemoveSourceItemResponses[keyof RemoveSourceItemResponses];

export type ReindexSourceItemData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        sourceId: string;
        itemId: string;
    };
    query?: never;
    url: '/api/sources/{sourceId}/items/{itemId}/index-attempts';
};

export type ReindexSourceItemResponses = {
    /**
     * Accepted
     */
    202: SourceOperation;
};

export type ReindexSourceItemResponse = ReindexSourceItemResponses[keyof ReindexSourceItemResponses];

export type ListSourceGroupsData = {
    body?: never;
    path: {
        sourceId: string;
    };
    query?: never;
    url: '/api/sources/{sourceId}/groups';
};

export type ListSourceGroupsResponses = {
    /**
     * OK
     */
    200: SourceGroupList;
};

export type ListSourceGroupsResponse = ListSourceGroupsResponses[keyof ListSourceGroupsResponses];

export type UpdateSourceGroupsData = {
    body: UpdateSourceGroupsRequest;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        sourceId: string;
    };
    query?: never;
    url: '/api/sources/{sourceId}/groups';
};

export type UpdateSourceGroupsResponses = {
    /**
     * No Content
     */
    204: void;
};

export type UpdateSourceGroupsResponse = UpdateSourceGroupsResponses[keyof UpdateSourceGroupsResponses];

export type DeleteSourceData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        sourceId: string;
    };
    query?: never;
    url: '/api/sources/{sourceId}/delete';
};

export type DeleteSourceResponses = {
    /**
     * Accepted
     */
    202: SourceOperation;
};

export type DeleteSourceResponse = DeleteSourceResponses[keyof DeleteSourceResponses];

export type CreateFileSourceData = {
    body: CreateFileSourceRequest;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path?: never;
    query?: never;
    url: '/api/sources/file';
};

export type CreateFileSourceResponses = {
    /**
     * Created
     */
    201: SourceDetail;
};

export type CreateFileSourceResponse = CreateFileSourceResponses[keyof CreateFileSourceResponses];

export type ListInvitationsData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'PENDING' | 'ACCEPTED' | 'EXPIRED' | 'REVOKED';
        email?: string;
        sort?: 'CREATED_AT_DESC' | 'CREATED_AT_ASC' | 'EMAIL_ASC' | 'EMAIL_DESC';
        page?: number;
        size?: number;
    };
    url: '/api/invitations';
};

export type ListInvitationsErrors = {
    /**
     * Invalid invitation list query
     */
    400: ApiProblem;
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor lacks USERS_MANAGE authority
     */
    403: ApiProblem;
};

export type ListInvitationsError = ListInvitationsErrors[keyof ListInvitationsErrors];

export type ListInvitationsResponses = {
    /**
     * A bounded page of invitation lifecycle records without plaintext secrets
     */
    200: InvitationPage;
};

export type ListInvitationsResponse = ListInvitationsResponses[keyof ListInvitationsResponses];

export type CreateInvitationData = {
    body: CreateInvitationRequest;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path?: never;
    query?: never;
    url: '/api/invitations';
};

export type CreateInvitationErrors = {
    /**
     * Invalid email
     */
    400: ApiProblem;
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor lacks USERS_MANAGE authority or the same-origin header is missing
     */
    403: ApiProblem;
    /**
     * A conflicting pending invitation already exists
     */
    409: ApiProblem;
    /**
     * Keycloak recipient activation is temporarily unavailable
     */
    503: ApiProblem;
};

export type CreateInvitationError = CreateInvitationErrors[keyof CreateInvitationErrors];

export type CreateInvitationResponses = {
    /**
     * Invitation created; the invitation URL is returned only in this response
     */
    201: IssuedInvitation;
};

export type CreateInvitationResponse = CreateInvitationResponses[keyof CreateInvitationResponses];

export type RotateInvitationData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        /**
         * Invitation identifier.
         */
        invitationId: string;
    };
    query?: never;
    url: '/api/invitations/{invitationId}/rotate';
};

export type RotateInvitationErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor lacks USERS_MANAGE authority or the same-origin header is missing
     */
    403: ApiProblem;
    /**
     * Invitation is no longer pending and available
     */
    410: ApiProblem;
};

export type RotateInvitationError = RotateInvitationErrors[keyof RotateInvitationErrors];

export type RotateInvitationResponses = {
    /**
     * Invitation rotated; the replacement URL is returned only in this response
     */
    200: IssuedInvitation;
};

export type RotateInvitationResponse = RotateInvitationResponses[keyof RotateInvitationResponses];

export type RevokeInvitationData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        /**
         * Invitation identifier.
         */
        invitationId: string;
    };
    query?: never;
    url: '/api/invitations/{invitationId}/revoke';
};

export type RevokeInvitationErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor lacks USERS_MANAGE authority or the same-origin header is missing
     */
    403: ApiProblem;
    /**
     * Invitation is no longer pending and available
     */
    410: ApiProblem;
};

export type RevokeInvitationError = RevokeInvitationErrors[keyof RevokeInvitationErrors];

export type RevokeInvitationResponses = {
    /**
     * Invitation revoked
     */
    204: void;
};

export type RevokeInvitationResponse = RevokeInvitationResponses[keyof RevokeInvitationResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        page?: number;
        size?: number;
    };
    url: '/api/groups';
};

export type ListGroupsErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor has no global or managed-Group read authority
     */
    403: ApiProblem;
};

export type ListGroupsError = ListGroupsErrors[keyof ListGroupsErrors];

export type ListGroupsResponses = {
    /**
     * A bounded, server-authorized Group page
     */
    200: GroupPage;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    body: CreateGroupRequest;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path?: never;
    query?: never;
    url: '/api/groups';
};

export type CreateGroupResponses = {
    /**
     * Group created
     */
    201: GroupSummary;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type RenameGroupData = {
    body: RenameGroupRequest;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/api/groups/{groupId}/rename';
};

export type RenameGroupResponses = {
    /**
     * Group renamed
     */
    200: GroupSummary;
};

export type RenameGroupResponse = RenameGroupResponses[keyof RenameGroupResponses];

export type ListGroupMembersData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: {
        search?: string;
        page?: number;
        size?: number;
    };
    url: '/api/groups/{groupId}/members';
};

export type ListGroupMembersResponses = {
    /**
     * A bounded Group member page
     */
    200: GroupMemberPage;
};

export type ListGroupMembersResponse = ListGroupMembersResponses[keyof ListGroupMembersResponses];

export type AddGroupMembersData = {
    body: AddGroupMembersRequest;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/api/groups/{groupId}/members';
};

export type AddGroupMembersResponses = {
    /**
     * Members added idempotently
     */
    204: void;
};

export type AddGroupMembersResponse = AddGroupMembersResponses[keyof AddGroupMembersResponses];

export type RemoveGroupMemberData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        groupId: string;
        actorId: string;
    };
    query?: never;
    url: '/api/groups/{groupId}/members/{actorId}/remove';
};

export type RemoveGroupMemberResponses = {
    /**
     * Member removed
     */
    204: void;
};

export type RemoveGroupMemberResponse = RemoveGroupMemberResponses[keyof RemoveGroupMemberResponses];

export type RemoveGroupManagerData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        groupId: string;
        actorId: string;
    };
    query?: never;
    url: '/api/groups/{groupId}/members/{actorId}/remove-manager';
};

export type RemoveGroupManagerResponses = {
    /**
     * Manager flag removed
     */
    204: void;
};

export type RemoveGroupManagerResponse = RemoveGroupManagerResponses[keyof RemoveGroupManagerResponses];

export type AssignGroupManagerData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        groupId: string;
        actorId: string;
    };
    query?: never;
    url: '/api/groups/{groupId}/members/{actorId}/assign-manager';
};

export type AssignGroupManagerResponses = {
    /**
     * Manager assigned
     */
    204: void;
};

export type AssignGroupManagerResponse = AssignGroupManagerResponses[keyof AssignGroupManagerResponses];

export type DeleteGroupData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/api/groups/{groupId}/delete';
};

export type DeleteGroupResponses = {
    /**
     * Group links and grants deleted
     */
    204: void;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type ReplaceGroupCapabilitiesData = {
    body: ReplaceGroupCapabilitiesRequest;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        groupId: string;
    };
    query?: never;
    url: '/api/groups/{groupId}/capabilities';
};

export type ReplaceGroupCapabilitiesResponses = {
    /**
     * Explicit grants replaced
     */
    204: void;
};

export type ReplaceGroupCapabilitiesResponse = ReplaceGroupCapabilitiesResponses[keyof ReplaceGroupCapabilitiesResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        status?: 'ACTIVE' | 'INACTIVE' | 'INVITED';
        role?: 'OWNER' | 'MEMBER';
        groupId?: string;
        sort?: 'NAME_ASC' | 'NAME_DESC' | 'EMAIL_ASC' | 'EMAIL_DESC' | 'STATUS_ASC' | 'STATUS_DESC' | 'ROLE_ASC' | 'ROLE_DESC';
        page?: number;
        size?: number;
    };
    url: '/api/users';
};

export type ListUsersErrors = {
    /**
     * Invalid user directory query
     */
    400: ApiProblem;
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor lacks USERS_MANAGE authority
     */
    403: ApiProblem;
};

export type ListUsersError = ListUsersErrors[keyof ListUsersErrors];

export type ListUsersResponses = {
    /**
     * A bounded page of current memberships and eligible pending invitations
     */
    200: UserPage;
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type ListSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sources';
};

export type ListSourcesResponses = {
    /**
     * OK
     */
    200: Array<SourceSummary>;
};

export type ListSourcesResponse = ListSourcesResponses[keyof ListSourcesResponses];

export type GetSourceData = {
    body?: never;
    path: {
        sourceId: string;
    };
    query?: never;
    url: '/api/sources/{sourceId}';
};

export type GetSourceResponses = {
    /**
     * OK
     */
    200: SourceDetail;
};

export type GetSourceResponse = GetSourceResponses[keyof GetSourceResponses];

export type ListSourceItemsData = {
    body?: never;
    path: {
        sourceId: string;
    };
    query?: never;
    url: '/api/sources/{sourceId}/items';
};

export type ListSourceItemsResponses = {
    /**
     * OK
     */
    200: Array<SourceItem>;
};

export type ListSourceItemsResponse = ListSourceItemsResponses[keyof ListSourceItemsResponses];

export type ListSourceIndexAttemptsData = {
    body?: never;
    path: {
        sourceId: string;
    };
    query?: {
        size?: number;
    };
    url: '/api/sources/{sourceId}/index-attempts';
};

export type ListSourceIndexAttemptsResponses = {
    /**
     * OK
     */
    200: Array<SourceOperation>;
};

export type ListSourceIndexAttemptsResponse = ListSourceIndexAttemptsResponses[keyof ListSourceIndexAttemptsResponses];

export type ListSourceGroupOptionsData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        page?: number;
        size?: number;
    };
    url: '/api/sources/group-options';
};

export type ListSourceGroupOptionsResponses = {
    /**
     * OK
     */
    200: SourceGroupPage;
};

export type ListSourceGroupOptionsResponse = ListSourceGroupOptionsResponses[keyof ListSourceGroupOptionsResponses];

export type GetSourceOperationData = {
    body?: never;
    path: {
        operationId: string;
    };
    query?: never;
    url: '/api/source-operations/{operationId}';
};

export type GetSourceOperationResponses = {
    /**
     * OK
     */
    200: SourceOperation;
};

export type GetSourceOperationResponse = GetSourceOperationResponses[keyof GetSourceOperationResponses];

export type GetCurrentInvitationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/invitations/current';
};

export type GetCurrentInvitationErrors = {
    /**
     * No available invitation continuation exists
     */
    410: ApiProblem;
};

export type GetCurrentInvitationError = GetCurrentInvitationErrors[keyof GetCurrentInvitationErrors];

export type GetCurrentInvitationResponses = {
    /**
     * Active invitation continuation
     */
    200: CurrentInvitation;
};

export type GetCurrentInvitationResponse = GetCurrentInvitationResponses[keyof GetCurrentInvitationResponses];

export type GetCurrentIdentityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/identity/me';
};

export type GetCurrentIdentityErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
};

export type GetCurrentIdentityResponses = {
    /**
     * The authenticated actor
     */
    200: CurrentIdentity;
};

export type GetCurrentIdentityResponse = GetCurrentIdentityResponses[keyof GetCurrentIdentityResponses];

export type GetGroupData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/api/groups/{groupId}';
};

export type GetGroupResponses = {
    /**
     * The server-authorized Group detail
     */
    200: GroupSummary;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type ListGroupSourcesData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: never;
    url: '/api/groups/{groupId}/sources';
};

export type ListGroupSourcesResponses = {
    /**
     * OK
     */
    200: GroupSources;
};

export type ListGroupSourcesResponse = ListGroupSourcesResponses[keyof ListGroupSourcesResponses];

export type ListGroupCandidatesData = {
    body?: never;
    path: {
        groupId: string;
    };
    query?: {
        search?: string;
        page?: number;
        size?: number;
    };
    url: '/api/groups/{groupId}/candidates';
};

export type ListGroupCandidatesResponses = {
    /**
     * A bounded candidate page
     */
    200: GroupMemberPage;
};

export type ListGroupCandidatesResponse = ListGroupCandidatesResponses[keyof ListGroupCandidatesResponses];

export type ListGroupCapabilitiesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/groups/capabilities';
};

export type ListGroupCapabilitiesResponses = {
    /**
     * Capability metadata for implemented consumers
     */
    200: GroupCapabilities;
};

export type ListGroupCapabilitiesResponse = ListGroupCapabilitiesResponses[keyof ListGroupCapabilitiesResponses];
