// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CreateInvitationRequest = {
    email: string;
};

export type Invitation = {
    id: string;
    email: string;
    status: 'PENDING' | 'ACCEPTED' | 'EXPIRED' | 'REVOKED';
    createdAt: string;
    expiresAt: string;
    acceptedActorId?: string | null;
    acceptedAt?: string | null;
    revokedAt?: string | null;
};

export type IssuedInvitation = {
    invitation: Invitation;
    /**
     * Relative same-origin capability URL returned only from create or rotate.
     */
    invitationUrl: string;
    /**
     * Observable delivery result for this issue or rotation operation.
     */
    delivery: 'ACTIVATION_EMAIL_SENT' | 'EXISTING_ACCOUNT' | 'RECOVERY_LINK_ONLY';
};

export type InvitationPage = {
    items: Array<Invitation>;
    page: number;
    size: number;
    totalItems: number;
    totalPages: number;
};

export type CurrentInvitation = {
    organizationDisplayName: string;
    expiresAt: string;
    continueUrl: string;
};

export type CurrentIdentity = {
    /**
     * Stable internal MemoryOS actor identifier.
     */
    actorId: string;
    /**
     * Active Organization context, or null when the actor has no active Organization membership.
     */
    organization: CurrentOrganization | null;
    /**
     * Canonical capabilities backed by current server enforcement.
     */
    capabilities: Array<'INVITATIONS_MANAGE'>;
};

export type CurrentOrganization = {
    /**
     * Display name of the actor's active Organization.
     */
    displayName: string;
    /**
     * Stable Organization membership role used for presentation.
     */
    role: 'OWNER' | 'MEMBER';
};

export type ApiProblem = {
    /**
     * Stable problem type for capability failures; omitted means RFC 9457 `about:blank`.
     */
    type?: string;
    /**
     * Short human-readable problem category.
     */
    title: string;
    /**
     * HTTP status code.
     */
    status: number;
    /**
     * Safe human-readable fallback detail.
     */
    detail: string;
    /**
     * Request path that produced the problem.
     */
    instance: string;
    /**
     * Stable capability-prefixed code; present only for expected capability failures.
     */
    code?: string;
};

export type ListInvitationsData = {
    body?: never;
    path?: never;
    query?: {
        status?: 'PENDING' | 'ACCEPTED' | 'EXPIRED' | 'REVOKED';
        email?: string;
        sort?: 'CREATED_AT_DESC' | 'CREATED_AT_ASC' | 'EMAIL_ASC' | 'EMAIL_DESC';
        page?: number;
        size?: number;
    };
    url: '/api/invitations';
};

export type ListInvitationsErrors = {
    /**
     * Invalid invitation list query
     */
    400: ApiProblem;
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor is not an active Organization owner
     */
    403: ApiProblem;
};

export type ListInvitationsError = ListInvitationsErrors[keyof ListInvitationsErrors];

export type ListInvitationsResponses = {
    /**
     * A bounded page of invitation lifecycle records without plaintext secrets
     */
    200: InvitationPage;
};

export type ListInvitationsResponse = ListInvitationsResponses[keyof ListInvitationsResponses];

export type CreateInvitationData = {
    body: CreateInvitationRequest;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path?: never;
    query?: never;
    url: '/api/invitations';
};

export type CreateInvitationErrors = {
    /**
     * Invalid email
     */
    400: ApiProblem;
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor is not an active Organization owner or the same-origin header is missing
     */
    403: ApiProblem;
    /**
     * A conflicting pending invitation already exists
     */
    409: ApiProblem;
    /**
     * Keycloak recipient activation is temporarily unavailable
     */
    503: ApiProblem;
};

export type CreateInvitationError = CreateInvitationErrors[keyof CreateInvitationErrors];

export type CreateInvitationResponses = {
    /**
     * Invitation created; the invitation URL is returned only in this response
     */
    201: IssuedInvitation;
};

export type CreateInvitationResponse = CreateInvitationResponses[keyof CreateInvitationResponses];

export type RotateInvitationData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        /**
         * Invitation identifier.
         */
        invitationId: string;
    };
    query?: never;
    url: '/api/invitations/{invitationId}/rotate';
};

export type RotateInvitationErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor is not an active Organization owner or the same-origin header is missing
     */
    403: ApiProblem;
    /**
     * Invitation is no longer pending and available
     */
    410: ApiProblem;
};

export type RotateInvitationError = RotateInvitationErrors[keyof RotateInvitationErrors];

export type RotateInvitationResponses = {
    /**
     * Invitation rotated; the replacement URL is returned only in this response
     */
    200: IssuedInvitation;
};

export type RotateInvitationResponse = RotateInvitationResponses[keyof RotateInvitationResponses];

export type GetCurrentInvitationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/invitations/current';
};

export type GetCurrentInvitationErrors = {
    /**
     * No available invitation continuation exists
     */
    410: ApiProblem;
};

export type GetCurrentInvitationError = GetCurrentInvitationErrors[keyof GetCurrentInvitationErrors];

export type GetCurrentInvitationResponses = {
    /**
     * Active invitation continuation
     */
    200: CurrentInvitation;
};

export type GetCurrentInvitationResponse = GetCurrentInvitationResponses[keyof GetCurrentInvitationResponses];

export type GetCurrentIdentityData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/identity/me';
};

export type GetCurrentIdentityErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
};

export type GetCurrentIdentityResponses = {
    /**
     * The authenticated actor
     */
    200: CurrentIdentity;
};

export type GetCurrentIdentityResponse = GetCurrentIdentityResponses[keyof GetCurrentIdentityResponses];

export type RevokeInvitationData = {
    body?: never;
    headers: {
        /**
         * Same-origin non-simple request guard for browser-session mutations.
         */
        'X-MemoryOS-CSRF': '1';
    };
    path: {
        /**
         * Invitation identifier.
         */
        invitationId: string;
    };
    query?: never;
    url: '/api/invitations/{invitationId}';
};

export type RevokeInvitationErrors = {
    /**
     * No accepted authentication is present
     */
    401: unknown;
    /**
     * The actor is not an active Organization owner or the same-origin header is missing
     */
    403: ApiProblem;
    /**
     * Invitation is no longer pending and available
     */
    410: ApiProblem;
};

export type RevokeInvitationError = RevokeInvitationErrors[keyof RevokeInvitationErrors];

export type RevokeInvitationResponses = {
    /**
     * Invitation revoked
     */
    204: void;
};

export type RevokeInvitationResponse = RevokeInvitationResponses[keyof RevokeInvitationResponses];
