package io.memoryos.api.chat;

import io.memoryos.chat.interpreter.InterpreterService;
import io.memoryos.iam.identity.IdentityContext;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import org.springframework.http.ContentDisposition;
import org.springframework.http.MediaType;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping(value = "/api/chat/file-artifacts", produces = MediaType.APPLICATION_JSON_VALUE)
@Tag(name = "Chat")
@ApiResponse(responseCode = "400", description = "Invalid file request", content = @Content(mediaType = MediaType.APPLICATION_PROBLEM_JSON_VALUE, schema = @Schema(ref = "#/components/schemas/ApiProblem")))
@ApiResponse(responseCode = "403", description = "Tenant membership or CSRF requirement not met", content = @Content(mediaType = MediaType.APPLICATION_PROBLEM_JSON_VALUE, schema = @Schema(ref = "#/components/schemas/ApiProblem")))
@ApiResponse(responseCode = "404", description = "File not accessible", content = @Content(mediaType = MediaType.APPLICATION_PROBLEM_JSON_VALUE, schema = @Schema(ref = "#/components/schemas/ApiProblem")))
@ApiResponse(responseCode = "503", description = "Storage unavailable", content = @Content(mediaType = MediaType.APPLICATION_PROBLEM_JSON_VALUE, schema = @Schema(ref = "#/components/schemas/ApiProblem")))
@ApiResponse(responseCode = "401", description = "Authentication required", content = @Content)
@SecurityRequirement(name = "browserSession")
@SecurityRequirement(name = "bearerAuth")
class ChatFileArtifactController {
    /** Only raster images display inline; every other generated file downloads under nosniff. */
    private static final Set<String> INLINE = Set.of("image/png", "image/jpeg", "image/webp");
    private final InterpreterService files;
    ChatFileArtifactController(InterpreterService files) { this.files = files; }

    @Schema(name = "ChatSpreadsheetPreview")
    record SpreadsheetPreviewResponse(List<SheetResponse> sheets) {}

    @Schema(name = "ChatSpreadsheetSheet")
    record SheetResponse(String name, String csv, boolean truncated) {}

    @GetMapping("/{artifactId}/preview")
    @Operation(operationId = "previewChatFileArtifactSpreadsheet",
            summary = "Read an owner-private generated xlsx as CSV text per sheet, each cut at a row boundary")
    @ApiResponse(responseCode = "200", description = "Sheets in workbook order",
            content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE, schema = @Schema(implementation = SpreadsheetPreviewResponse.class)))
    SpreadsheetPreviewResponse preview(@Parameter(hidden = true) @AuthenticationPrincipal IdentityContext identity,
            @PathVariable UUID artifactId, HttpServletResponse response) {
        var sheets = files.spreadsheet(identity.actorId(), artifactId).stream()
                .map(sheet -> new SheetResponse(sheet.name(), sheet.csv(), sheet.truncated())).toList();
        response.setHeader("Cache-Control", "no-store");
        return new SpreadsheetPreviewResponse(sheets);
    }

    @GetMapping(value = "/{artifactId}/content", produces = MediaType.APPLICATION_OCTET_STREAM_VALUE)
    @Operation(operationId = "getChatFileArtifact", summary = "Read an owner-private file generated by Code Interpreter")
    @ApiResponse(responseCode = "200", description = "Generated file bytes",
            content = @Content(schema = @Schema(type = "string", format = "binary")))
    void content(@Parameter(hidden = true) @AuthenticationPrincipal IdentityContext identity,
            @PathVariable UUID artifactId, HttpServletResponse response) throws IOException {
        var served = files.open(identity.actorId(), artifactId);
        try (var content = served.content()) {
            boolean inline = INLINE.contains(served.mediaType());
            response.setContentType(served.mediaType());
            response.setHeader("Cache-Control", "no-store");
            response.setHeader("X-Content-Type-Options", "nosniff");
            response.setHeader("Content-Disposition", (inline ? ContentDisposition.inline() : ContentDisposition.attachment())
                    .filename(served.filename(), java.nio.charset.StandardCharsets.UTF_8).build().toString());
            response.setContentLengthLong(content.metadata().sizeBytes());
            content.inputStream().transferTo(response.getOutputStream());
        }
    }
}
