package io.memoryos.connector;

public enum SourceRunStatus {
    QUEUED, ACQUIRING, RETRY_SCHEDULED, RECOVERY_PENDING, INDEXING, SUCCEEDED,
    COMPLETED_WITH_ERRORS, FAILED, SUPERSEDED, CANCELLED, UNKNOWN
}
