package io.memoryos.chat.application;

import io.memoryos.chat.ChatException;
import io.memoryos.chat.ChatMessage;
import io.memoryos.chat.ChatSession;
import io.memoryos.chat.persistence.JdbcChatArtifactRepository;
import io.memoryos.chat.persistence.JdbcChatRepository;
import io.memoryos.shared.ActorId;
import io.memoryos.iam.tenant.TenantAccessResolver;
import io.memoryos.shared.TenantId;
import io.memoryos.objectstorage.ObjectStorage;
import io.memoryos.objectstorage.ObjectStorageException;
import io.memoryos.objectstorage.ObjectStorageFailureCode;
import io.memoryos.objectstorage.ObjectWriteService;
import org.jspecify.annotations.Nullable;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

/**
 * Branching a conversation into a new one (MEM-153): the selected path up to one message is copied into a
 * conversation of the caller's own, which then goes its own way. The copy is a copy rather than a reference —
 * including the bytes of every generated file and image along it — so deleting either conversation leaves the
 * other whole, which is what the origin link in the header promises.
 */
@Service
public class ChatBranchService {
    /** A branch is a conversation to carry on, not an archive: a very long path is refused rather than truncated. */
    private static final int MAX_MESSAGES = 1000;
    /** What the copy may cost in generated bytes, which are written one object at a time. */
    private static final int MAX_ARTIFACTS = 50;
    private static final long MAX_ARTIFACT_BYTES = 30L * 1024 * 1024;
    /** The storage adapter writes at most this much from memory, so a larger artifact cannot be copied at all. */
    private static final long MAX_ONE_ARTIFACT_BYTES = 32L * 1024 * 1024;
    private static final String TITLE_PREFIX = "Branch of ";
    private static final int MAX_TITLE = 200;

    private final TenantAccessResolver tenants;
    private final JdbcChatRepository chats;
    private final JdbcChatArtifactRepository library;
    private final ObjectStorage storage;
    private final ObjectWriteService writes;
    private final TransactionTemplate tx;

    public ChatBranchService(TenantAccessResolver tenants, JdbcChatRepository chats,
                             JdbcChatArtifactRepository library, ObjectStorage storage, ObjectWriteService writes,
                             PlatformTransactionManager transactionManager) {
        this.tenants = tenants;
        this.chats = chats;
        this.library = library;
        this.storage = storage;
        this.writes = writes;
        this.tx = new TransactionTemplate(transactionManager);
    }

    /**
     * Copies {@code sessionId}'s selected path, up to and including {@code messageId}, into a new conversation.
     *
     * <p>A branch always ends on an answer: naming a question copies the answer that followed it, because a
     * question with no answer is a turn that was never taken and there would be nothing to carry on from. A
     * message still being answered, a message on a path that is not the selected one, and a conversation the
     * caller does not own are all refused.
     */
    public ChatSession branch(ActorId actor, UUID sessionId, UUID messageId) {
        return branch(actor, sessionId, messageId, null);
    }

    /**
     * {@code title} is what the browser calls the branch, so the name reads in the language the person is
     * using; without one the server falls back to its own prefix. It is trimmed and bounded like any title.
     */
    public ChatSession branch(ActorId actor, UUID sessionId, UUID messageId,
                              @Nullable String title) {
        var tenant = tenants.findActiveTenant(actor).orElseThrow(ChatException::unavailable);
        var origin = chats.findOwned(tenant, actor, sessionId, false).orElseThrow(ChatException::unavailable);
        // A branch outlives what it was taken from, which is exactly what a temporary conversation promised
        // would not happen; there is nothing to copy it into.
        if (origin.temporary()) throw ChatException.invalid("A temporary conversation cannot be branched.");
        if (!chats.onSelectedBranch(origin, messageId)) throw ChatException.unavailable();
        var path = pathTo(origin, messageId);
        // Every copy's id is chosen up front: a question's row names the answer that follows it, a message names
        // its child, and the staged artifacts have to know which copy they will belong to.
        Map<UUID, UUID> copies = new LinkedHashMap<>();
        for (var message : path) copies.put(message.id(), UUID.randomUUID());

        // Storage IO runs outside the transaction, and what it wrote is discarded when the copy cannot commit.
        var staged = new ArrayList<Staged>();
        try {
            stage(tenant, path, copies, staged);
            var branch = Objects.requireNonNull(tx.execute(ignored -> {
                var created = chats.createBranch(tenant, actor, origin, messageId, title(origin.title(), title));
                chats.copyMessages(origin.id(), created.id(), plan(path, copies, created.rootMessageId()));
                chats.selectChild(created.id(), created.rootMessageId(), copies.get(path.getFirst().id()));
                for (var copy : staged) {
                    library.copyArtifact(tenant, copy.artifact(), UUID.randomUUID(), copy.messageCopyId(),
                            copy.staged().object().id().value(), copy.staged().object().key());
                    writes.adopt(tenant, copy.staged());
                }
                return created;
            }));
            staged.clear();
            return branch;
        } finally {
            // Anything still listed belongs to a copy that did not commit, so its bytes are released at once.
            for (var copy : staged) discard(tenant, copy);
        }
    }

    /** The selected path from the root up to the named message, extended to the answer that closes it. */
    private List<ChatMessage> pathTo(ChatSession origin, UUID messageId) {
        var history = chats.history(origin, null, MAX_MESSAGES + 2);
        var path = new ArrayList<ChatMessage>();
        for (int index = 0; index < history.size(); index++) {
            var message = history.get(index);
            path.add(message);
            if (!message.id().equals(messageId)) continue;
            if (message.role() == ChatMessage.Role.USER) {
                if (index + 1 >= history.size())
                    throw ChatException.invalid("This question has no answer to branch from.");
                path.add(history.get(index + 1));
            }
            break;
        }
        if (path.stream().noneMatch(message -> message.id().equals(messageId))) throw ChatException.unavailable();
        if (path.size() > MAX_MESSAGES) throw ChatException.invalid("This conversation is too long to branch.");
        if (path.stream().anyMatch(message -> message.status() == ChatMessage.Status.RUNNING))
            throw ChatException.conflict();
        return path;
    }

    /**
     * What to insert: the path is a chain, so each copy's parent is the copy before it and the first copy hangs
     * off the branch's own root.
     */
    private List<JdbcChatRepository.MessageCopy> plan(List<ChatMessage> path, Map<UUID, UUID> copies, UUID root) {
        var plan = new ArrayList<JdbcChatRepository.MessageCopy>(path.size());
        for (int index = 0; index < path.size(); index++) {
            var message = path.get(index);
            var next = index + 1 < path.size() ? path.get(index + 1) : null;
            boolean question = message.role() == ChatMessage.Role.USER;
            if (question && next == null) throw ChatException.invalid("This question has no answer to branch from.");
            plan.add(new JdbcChatRepository.MessageCopy(message.id(), copies.get(message.id()),
                    index == 0 ? root : copies.get(path.get(index - 1).id()),
                    next == null ? null : copies.get(next.id()),
                    question ? UUID.randomUUID() : null,
                    question ? copies.get(next.id()) : null));
        }
        return plan;
    }

    /** Reads the bytes of every artifact along the path and writes them as the branch's own objects. */
    private void stage(TenantId tenant, List<ChatMessage> path, Map<UUID, UUID> copies, List<Staged> staged) {
        long bytes = 0;
        for (var message : path) {
            for (var artifact : library.messageArtifacts(tenant, message.id())) {
                if (staged.size() >= MAX_ARTIFACTS)
                    throw ChatException.invalid("This conversation holds too many generated files to branch.");
                if (artifact.sizeBytes() > MAX_ONE_ARTIFACT_BYTES || bytes + artifact.sizeBytes() > MAX_ARTIFACT_BYTES)
                    throw ChatException.invalid("This conversation's generated files are too large to branch.");
                bytes += artifact.sizeBytes();
                var specification =
                        new ObjectWriteService.Specification(artifact.filename(), artifact.mediaType(), false);
                var written = writes.stage(tenant, specification, read(artifact));
                staged.add(new Staged(artifact, written, copies.get(message.id())));
            }
        }
    }

    private byte[] read(JdbcChatArtifactRepository.MessageArtifact artifact) {
        try (var content = storage.open(artifact.key())) {
            byte[] bytes = content.inputStream().readNBytes((int) MAX_ONE_ARTIFACT_BYTES + 1);
            // A file whose bytes are gone cannot be copied, and a branch missing them is not the conversation.
            if (bytes.length != artifact.sizeBytes()) throw ChatException.unavailable();
            return bytes;
        } catch (ObjectStorageException failure) {
            if (failure.code() == ObjectStorageFailureCode.NOT_FOUND) throw ChatException.unavailable();
            throw failure;
        } catch (IOException failure) {
            throw new UncheckedIOException(failure);
        }
    }

    private void discard(TenantId tenant, Staged copy) {
        try {
            writes.discard(tenant, copy.staged());
        } catch (RuntimeException ignored) {
            // The cleanup sweep releases what a discard could not; reporting the branch's failure matters more.
        }
    }

    /** A title says where the branch came from, and stays inside what a title may hold. */
    private String title(String origin, @Nullable String requested) {
        String title = requested == null || requested.isBlank() ? TITLE_PREFIX + origin : requested.strip();
        if (title.indexOf('\0') >= 0) throw ChatException.invalid("Invalid title.");
        return title.length() <= MAX_TITLE ? title : title.substring(0, MAX_TITLE);
    }

    private record Staged(JdbcChatArtifactRepository.MessageArtifact artifact, ObjectWriteService.StagedObject staged,
                          UUID messageCopyId) {}
}
