package vn.edu.swd392.vpmcp.tools;

final class ContextDiagramSchemas {
  static final String CREATE_CONTEXT =
      "{"
          + "\"type\":\"object\","
          + "\"properties\":{"
          + "\"spec\":{"
          + "\"type\":\"object\","
          + "\"properties\":{"
          + "\"operationId\":{\"type\":\"string\",\"minLength\":8,\"maxLength\":128,"
          + "\"pattern\":\"^[A-Za-z0-9._:-]+$\","
          + "\"description\":\"Stable idempotency key reused only for an identical Context Diagram specification\"},"
          + "\"diagramName\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":160},"
          + "\"systemName\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":160},"
          + "\"entities\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":24,\"items\":{"
          + "\"type\":\"object\",\"properties\":{"
          + "\"id\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80,\"pattern\":\"^[A-Za-z0-9._:-]+$\"},"
          + "\"name\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120},"
          + "\"side\":{\"type\":\"string\",\"enum\":[\"AUTO\",\"LEFT\",\"RIGHT\",\"TOP\",\"BOTTOM\"]},"
          + "\"factIds\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80}}"
          + "},\"required\":[\"id\",\"name\"],\"additionalProperties\":false}},"
          + "\"flows\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":80,\"items\":{"
          + "\"type\":\"object\",\"properties\":{"
          + "\"id\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80,\"pattern\":\"^[A-Za-z0-9._:-]+$\"},"
          + "\"name\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":160},"
          + "\"from\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"to\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"factIds\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80}}"
          + "},\"required\":[\"id\",\"name\",\"from\",\"to\"],\"additionalProperties\":false}},"
          + "\"layout\":{\"type\":\"object\",\"properties\":{"
          + "\"centerX\":{\"type\":\"integer\",\"minimum\":300,\"maximum\":4000},"
          + "\"centerY\":{\"type\":\"integer\",\"minimum\":250,\"maximum\":4000},"
          + "\"processWidth\":{\"type\":\"integer\",\"minimum\":220,\"maximum\":900},"
          + "\"processHeight\":{\"type\":\"integer\",\"minimum\":120,\"maximum\":600},"
          + "\"entityWidth\":{\"type\":\"integer\",\"minimum\":140,\"maximum\":600},"
          + "\"entityHeight\":{\"type\":\"integer\",\"minimum\":60,\"maximum\":300},"
          + "\"horizontalGap\":{\"type\":\"integer\",\"minimum\":100,\"maximum\":1000},"
          + "\"verticalGap\":{\"type\":\"integer\",\"minimum\":90,\"maximum\":600},"
          + "\"connectorStyle\":{\"type\":\"string\",\"enum\":[\"CURVE\",\"RECTILINEAR\",\"OBLIQUE\"]}"
          + "},\"additionalProperties\":false}"
          + "},"
          + "\"required\":[\"operationId\",\"diagramName\",\"systemName\",\"entities\",\"flows\"],"
          + "\"additionalProperties\":false"
          + "},"
          + "\"dryRun\":{\"type\":\"boolean\","
          + "\"description\":\"Validate and plan without mutating Visual Paradigm\"}"
          + "},"
          + "\"required\":[\"spec\",\"dryRun\"],"
          + "\"additionalProperties\":false"
          + "}";

  private ContextDiagramSchemas() {}
}
