package vn.edu.swd392.vpmcp.tools;

final class UseCaseDiagramSchemas {
  static final String CREATE_USE_CASE =
      "{"
          + "\"type\":\"object\",\"properties\":{"
          + "\"spec\":{\"type\":\"object\",\"properties\":{"
          + "\"operationId\":{\"type\":\"string\",\"minLength\":8,\"maxLength\":128,\"pattern\":\"^[A-Za-z0-9._:-]+$\"},"
          + "\"diagramName\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":160},"
          + "\"systemName\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":160},"
          + "\"facts\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":120,\"items\":{\"type\":\"object\",\"properties\":{"
          + "\"id\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"text\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":1000}"
          + "},\"required\":[\"id\",\"text\"],\"additionalProperties\":false}},"
          + "\"actors\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":16,\"items\":{\"type\":\"object\",\"properties\":{"
          + "\"id\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"name\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120},"
          + "\"side\":{\"type\":\"string\",\"enum\":[\"LEFT\",\"RIGHT\"]},"
          + "\"factIds\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80}}"
          + "},\"required\":[\"id\",\"name\",\"side\",\"factIds\"],\"additionalProperties\":false}},"
          + "\"useCases\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":48,\"items\":{\"type\":\"object\",\"properties\":{"
          + "\"id\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"name\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":120},"
          + "\"description\":{\"type\":\"string\",\"maxLength\":500},"
          + "\"lane\":{\"type\":\"string\",\"enum\":[\"LEFT\",\"RIGHT\"]},"
          + "\"group\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"abstractUseCase\":{\"type\":\"boolean\"},"
          + "\"factIds\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80}}"
          + "},\"required\":[\"id\",\"name\",\"description\",\"lane\",\"group\",\"abstractUseCase\",\"factIds\"],\"additionalProperties\":false}},"
          + "\"associations\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":120,\"items\":{\"type\":\"object\",\"properties\":{"
          + "\"id\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"actorId\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"useCaseId\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"factIds\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80}}"
          + "},\"required\":[\"id\",\"actorId\",\"useCaseId\",\"factIds\"],\"additionalProperties\":false}},"
          + "\"relationships\":{\"type\":\"array\",\"maxItems\":80,\"items\":{\"type\":\"object\",\"properties\":{"
          + "\"id\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"type\":{\"type\":\"string\",\"enum\":[\"INCLUDE\",\"EXTEND\",\"GENERALIZATION\"]},"
          + "\"from\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"to\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80},"
          + "\"condition\":{\"type\":\"string\",\"maxLength\":240},"
          + "\"rationale\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":500},"
          + "\"factIds\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":80}}"
          + "},\"required\":[\"id\",\"type\",\"from\",\"to\",\"condition\",\"rationale\",\"factIds\"],\"additionalProperties\":false}},"
          + "\"layout\":{\"type\":\"object\",\"properties\":{"
          + "\"boundaryX\":{\"type\":\"integer\",\"minimum\":300,\"maximum\":3000},"
          + "\"boundaryY\":{\"type\":\"integer\",\"minimum\":20,\"maximum\":1000},"
          + "\"boundaryWidth\":{\"type\":\"integer\",\"minimum\":650,\"maximum\":2200},"
          + "\"useCaseWidth\":{\"type\":\"integer\",\"minimum\":160,\"maximum\":500},"
          + "\"useCaseHeight\":{\"type\":\"integer\",\"minimum\":45,\"maximum\":160},"
          + "\"rowGap\":{\"type\":\"integer\",\"minimum\":15,\"maximum\":180},"
          + "\"groupGap\":{\"type\":\"integer\",\"minimum\":0,\"maximum\":300},"
          + "\"topPadding\":{\"type\":\"integer\",\"minimum\":50,\"maximum\":300},"
          + "\"bottomPadding\":{\"type\":\"integer\",\"minimum\":40,\"maximum\":300},"
          + "\"actorWidth\":{\"type\":\"integer\",\"minimum\":40,\"maximum\":350},"
          + "\"actorHeight\":{\"type\":\"integer\",\"minimum\":90,\"maximum\":300},"
          + "\"actorGap\":{\"type\":\"integer\",\"minimum\":100,\"maximum\":700},"
          + "\"connectorStyle\":{\"type\":\"string\",\"enum\":[\"OBLIQUE\",\"RECTILINEAR\"]}"
          + "},\"additionalProperties\":false}"
          + "},"
          + "\"required\":[\"operationId\",\"diagramName\",\"systemName\",\"facts\",\"actors\",\"useCases\",\"associations\",\"relationships\"],"
          + "\"additionalProperties\":false},"
          + "\"dryRun\":{\"type\":\"boolean\"}},"
          + "\"required\":[\"spec\",\"dryRun\"],\"additionalProperties\":false}";

  private UseCaseDiagramSchemas() {}
}
