/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessNotProvisionedRouteImport } from './routes/access-not-provisioned'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessNotProvisionedRoute = AccessNotProvisionedRouteImport.update({
  id: '/access-not-provisioned',
  path: '/access-not-provisioned',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-not-provisioned': typeof AccessNotProvisionedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-not-provisioned': typeof AccessNotProvisionedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-not-provisioned': typeof AccessNotProvisionedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/access-not-provisioned'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/access-not-provisioned'
  id: '__root__' | '/' | '/access-not-provisioned'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessNotProvisionedRoute: typeof AccessNotProvisionedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-not-provisioned': {
      id: '/access-not-provisioned'
      path: '/access-not-provisioned'
      fullPath: '/access-not-provisioned'
      preLoaderRoute: typeof AccessNotProvisionedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessNotProvisionedRoute: AccessNotProvisionedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
