import { render, screen, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { QueryClientProvider } from "@tanstack/react-query";
import { HttpResponse } from "msw";
import { describe, expect, it, vi } from "vitest";
import { handleListUsageReports, handleRequestUsageReport } from "@/lib/hey-api/msw.gen";
import type { UsageReport } from "@/lib/hey-api/types.gen";
import { createMemoryOsQueryClient } from "@/lib/query-client";
import { server } from "@/test/msw";
import { UsageReports } from "./usage-reports";

const report = (overrides: Partial<UsageReport>): UsageReport => ({
  id: "3f0c1a9e-0000-4000-8000-000000000001",
  from: "2026-08-01",
  to: "2026-08-31",
  status: "READY",
  requester: "Trần Thu Hà",
  sizeBytes: 48_213,
  hasPdf: true,
  failure: null,
  createdAt: "2026-09-01T02:14:00Z",
  finishedAt: "2026-09-01T02:14:09Z",
  ...overrides,
});

function mount(list: UsageReport[] | "error") {
  const posted: unknown[] = [];
  server.use(
    handleRequestUsageReport(async ({ request }) => {
      posted.push(await request.json());
      return HttpResponse.json(report({ status: "PENDING" }), { status: 202 });
    }),
    // A refusal is not retried, so the failure shows at once.
    list === "error"
      ? handleListUsageReports(() => new HttpResponse(null, { status: 403 }))
      : handleListUsageReports({ body: list }),
  );
  render(
    <QueryClientProvider client={createMemoryOsQueryClient()}>
      <UsageReports />
    </QueryClientProvider>,
  );
  return posted;
}

describe("usage reports", () => {
  it("lists ready reports with a download link and who asked for them", async () => {
    mount([report({}), report({ id: "3f0c1a9e-0000-4000-8000-000000000002", hasPdf: false })]);
    const links = await screen.findAllByRole("link", { name: /Download report for/ });
    expect(links[0]).toHaveAttribute(
      "href",
      "/api/ai-costs/reports/3f0c1a9e-0000-4000-8000-000000000001/content",
    );
    expect(screen.getAllByText(/Generated by Trần Thu Hà/)).toHaveLength(2);
    expect(screen.getByText("CSV files only")).toBeVisible();
  });

  it("shows a report being built, and blocks a second request meanwhile", async () => {
    mount([report({ status: "RUNNING", createdAt: new Date().toISOString() })]);
    expect(await screen.findByText("Preparing report…")).toBeVisible();
    expect(screen.getByRole("button", { name: "Generating…" })).toBeDisabled();
    expect(screen.queryByRole("link")).toBeNull();
  });

  it("names a report that failed without offering a download", async () => {
    mount([report({ status: "FAILED", failure: "The report could not be generated." })]);
    expect(await screen.findByText("The report could not be generated.")).toBeVisible();
    expect(screen.queryByRole("link")).toBeNull();
  });

  it("asks for a period and requests a report for it", async () => {
    const posted = mount([]);
    expect(
      await screen.findByText("No reports yet. Pick a period and generate your first one."),
    ).toBeVisible();
    await userEvent.click(screen.getByRole("button", { name: "Generate report" }));
    const menu = await screen.findByRole("menu");
    await userEvent.click(within(menu).getByRole("menuitem", { name: "Last month" }));
    await vi.waitFor(() => expect(posted).toHaveLength(1));
    expect(posted[0]).toMatchObject({ from: expect.stringMatching(/^\d{4}-\d{2}-01$/) });
  });

  it("offers a retry when the list cannot be read", async () => {
    mount("error");
    expect(await screen.findByRole("alert")).toHaveTextContent("Failed to load usage reports.");
    expect(screen.getByRole("button", { name: "Try again" })).toBeVisible();
  });
});
